[package]
name = "nmf"
description = "Non-negative matrix factorization."
version = "0.1.0"
authors = ["Craig Wilkinson <craig@crwi.uk>"]
edition = "2018"
repository = "https://github.com/curlywurlycraig/nmf"

[dependencies]
rulinalg = "0.4.2"
