[package]
name = "nmf"
version = "0.1.0"
authors = ["Craig Wilkinson <curlywurlycraig@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rulinalg = "0.4.2"
